"""
Regenerate the root UNVERIFIED.md burn-down list.

Nobody hand-edits UNVERIFIED.md -- it is generated from two sources: the
derived unverified-field set in tests/truth.py (which fields have no
captured option list) and the hand-kept non-field unknowns in
tests/allowlist.py. Grouped by what unblocks each row, because the burn-down
is server-session-shaped, not skill-shaped: most rows clear the moment
someone has an authenticated session and opens the right screen once.

Run after adding a skill with a `## Unverified` table, or after changing
tests/allowlist.py:

    python tools/rollup_unverified.py           # check + rewrite
    python tools/rollup_unverified.py --check   # exit 1 if out of date, no write
"""
from __future__ import annotations

import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO))

from tests.locate_qcli import resolve as _resolve_qcli  # noqa: E402

try:
    _resolve_qcli()
except RuntimeError as e:
    print(e, file=sys.stderr)
    raise SystemExit(4)

from tests import truth  # noqa: E402
from tests import skillmd  # noqa: E402
from tests.allowlist import NON_FIELD_UNKNOWNS  # noqa: E402
from tests.conftest import skill_dirs  # noqa: E402

FIELD_UNBLOCK = {
    "agentId": "`qcli agents list` returning rows",
    "automationId": "`qcli rpa list` returning rows",
    "operation": "one look at the DocumentAI node in the designer",
    "taskType": "one look at the HitlTask node in the designer",
    "assignTo": "one look at the HitlTask node in the designer",
    "template": "one look at the HitlTask node in the designer",
}

RUNTIME_UNBLOCK = {
    "UV-RUNTIME-01": "any authenticated session",
    "UV-RUNTIME-02": "one successful `qcli flow run`",
}


def _table_rows_from_skills() -> dict[str, list[str]]:
    """Parse every `## Unverified` markdown table across all skills."""
    rows_by_unblock: dict[str, list[str]] = {}
    for skill in skill_dirs():
        for md_path in sorted(skill.glob("*.md")):
            doc = skillmd.parse(md_path)
            lines = doc.body_lines
            in_table = False
            for line in lines:
                if line.strip().lower().startswith("## unverified"):
                    in_table = True
                    continue
                if in_table and line.startswith("## "):
                    break
                if not in_table or not line.strip().startswith("|"):
                    continue
                cells = [c.strip() for c in line.strip().strip("|").split("|")]
                if len(cells) < 5 or cells[0] in ("ID", "----", ""):
                    continue
                if set(cells[0]) <= {"-", ":"}:
                    continue
                uv_id, claim, why, how, status = cells[:5]
                field = None
                for f in truth.unverified_fields():
                    if f in claim:
                        field = f
                        break
                unblock = FIELD_UNBLOCK.get(field) or RUNTIME_UNBLOCK.get(uv_id) or "manual investigation"
                rows_by_unblock.setdefault(unblock, []).append(
                    f"- `{uv_id}` ({skill.name}/{md_path.name}) {claim} -- {status}"
                )
    return rows_by_unblock


def build() -> str:
    rows = _table_rows_from_skills()
    seen_ids = {line.split("`")[1] for group in rows.values() for line in group}

    for uv_id, claim, why, how in NON_FIELD_UNKNOWNS:
        if uv_id in seen_ids:
            continue  # a skill already carries a more specific row for this id
        unblock = RUNTIME_UNBLOCK.get(uv_id, "manual investigation")
        rows.setdefault(unblock, []).append(f"- `{uv_id}` (repo-wide) {claim} -- open")

    lines = [
        "# Unverified claims",
        "",
        "Generated by `tools/rollup_unverified.py`. Do not hand-edit -- edit the",
        "`## Unverified` table in the relevant skill, or `tests/allowlist.py` for",
        "repo-wide unknowns, then regenerate.",
        "",
        "Every row here is something the offline harness cannot settle. Fixtures",
        "that need one of these values use a documented sentinel",
        f"(`{truth.SENTINEL_UUID}` for ids, `{truth.SENTINEL_TEXT}` for enums) rather",
        "than a plausible-looking fake, so `grep` finds every open row.",
        "",
    ]
    for unblock in sorted(rows):
        lines.append(f"## Unblocked by: {unblock}")
        lines.append("")
        lines.extend(sorted(rows[unblock]))
        lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def main() -> int:
    check_only = "--check" in sys.argv
    content = build()
    target = REPO / "UNVERIFIED.md"
    current = target.read_text(encoding="utf-8") if target.is_file() else ""
    if content == current:
        print("UNVERIFIED.md is up to date")
        return 0
    if check_only:
        print("UNVERIFIED.md is out of date -- run: python tools/rollup_unverified.py", file=sys.stderr)
        return 1
    target.write_text(content, encoding="utf-8", newline="\n")
    print(f"wrote {target}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
